title: #TVSunnah
description: Mr.Brown is a responsive jekyll theme
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: #"/mr-brown" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: nikyusof

# Social settings
twitter_url: https://twitter.com/tvsunnah
facebook_url: https://facebook.com/TVSunnah-191028304267964/
instagram_url: https://instagram.com/tvsunnah
youtube_url: https://youtube.com/tvsunnah/
